# DAY 1 - INTRO TO NUMPY

Numpy is an open source library for python used to do scientific calculations.

In [1]:
import numpy as np

In [2]:
a = [1,2,3]
type(a)

list

In [ ]:
b = np.array(a)
print(type(b))
b

<class 'numpy.ndarray'>


array([1, 2, 3])

In [7]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
b=np.array(a)
print(type(b))
b


<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#Row_1: [1, 2, 3]
#Row_2: [4, 5, 6]
#Row_3: [7, 8, 9]
#col_1: [1, 4, 7]
#col_2: [2, 5, 8]
#col_3: [3, 6, 9]

In [ ]:
print("Total elements are",b.size) #total elements(rows*columns)
print("Total rows and columns are:",b.shape) #rows and columns
print("Dimension:",b.ndim) #number of dimensions

Total elements are 9
Total arows and columns are: (3, 3)
Dimension: 2


In [ ]:
a=[1,2,3]
a*2 #doubling the list

[1, 2, 3, 1, 2, 3]

In [ ]:
b= np.array(a)
b*2 #elementwise multiplication

array([2, 4, 6])

Functions in Numpy

1. zeros() -> it will create an array in which all elements are zero.

In [21]:
a = np.zeros(3)
a


array([0., 0., 0.])

In [23]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

2. ones() -> Will create an array in which all elements are one.

In [24]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

3. eye(): will create an identity matrix

In [27]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. diag(): we can give custom values for diagonal elements.

In [33]:
a = np.array([1,45,67,99])

b = np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 99]])

5. randint() -> provides random integers in given range. 
 Syntax:np.random.randint(min_value,max_value,no. of elements)

In [34]:
a= np.random.randint(1,9,3)
a

array([5, 1, 8], dtype=int32)

6. rand()-> it will create an array in which random numbers will be in range b/w 0 to 1.

In [36]:
a= np.random.rand(5)
a

array([0.82101033, 0.60021024, 0.64885514, 0.86157157, 0.89061967])

7. seed() -> it will fix your random generated numbers.

In [45]:
np.random.seed(24)
a=np.random.randint(1,8,3)
a


array([3, 4, 1], dtype=int32)

8.  view and copy ->
      #->view : modification in original data.
      #->copy : changes in duplicate data will not reflect in original data.


In [ ]:
#view
a = np.array([1, 2, 3,4,3,5,2,5,6,6])
b= a[0:5]
b[:]=0
a 
# values in og dta will be changed as view is created on original data


array([0, 0, 0, 0, 0, 5, 2, 5, 6, 6])

In [ ]:
#copy
a = np.array([1, 2, 3,4,3,5,2,5,6,6])
b= a[0:5].copy()
b[:]=0
a
#values in og data will not be changed as copy is created on original data


array([1, 2, 3, 4, 3, 5, 2, 5, 6, 6])

### Reshaping an array
    condition : n(rows) * n(cols) = n(total elements)

In [53]:
a= np.random.randint(1,9,12)
a

array([2, 5, 4, 8, 5, 8, 4, 3, 4, 4, 4, 4], dtype=int32)

In [54]:
b=a.reshape(3,4)
b 

array([[2, 5, 4, 8],
       [5, 8, 4, 3],
       [4, 4, 4, 4]], dtype=int32)

In [56]:
b = a.reshape(6,2)
b

array([[2, 5],
       [4, 8],
       [5, 8],
       [4, 3],
       [4, 4],
       [4, 4]], dtype=int32)

Operations on Array

In [63]:
a = np.arange(0,11,2)
a


array([ 0,  2,  4,  6,  8, 10])

In [65]:
a= np.arange(1,5).reshape(2,2)
b= np.arange(5,9).reshape(2,2)
print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [66]:
a+b

array([[ 6,  8],
       [10, 12]])

In [70]:
a-b

array([[-4, -4],
       [-4, -4]])

In [71]:
#simple multiplication
a*b

array([[ 5, 12],
       [21, 32]])

In [67]:
#matrix multiplication
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
a%b #modulus operator gives the remainder of the division of corresponding elements

array([[1, 2],
       [3, 4]])

In [ ]:
a/b #elementwise division

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a**2 #square of each element

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
a**3 #cube of each element

array([[ 1,  8],
       [27, 64]])

#### Hstack() and vstack():
    1.hstack() : combines 2 or more arrays horizontally
    2.vstack() : combines 2 or more arrays vertically
    

In [78]:
a=np.array([1,2,3])
b=np.arange(4,7)
c=np.arange(7,10)


In [79]:
np.hstack((a,b,c)) #horizontal stacking

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.vstack((a,b,c)) #vertical stacking 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])