In [1]:
import numpy as np
import pandas as pd

# Text Representation

In [3]:
#1. Bag of words
# We use Count Vectorrizer to convert text into a bag of words representation. This will create a matrix where each row represents a document and each column represents a word from the vocabulary. The values in the matrix indicate the frequency of each word in the corresponding document.

In [4]:
df = pd.DataFrame({
    'Text': [
        'people watch cricket','player was player',
        'people write comment','cricket play comment']
    ,'output':[1,1,0,0]
})

In [5]:
df

,Text,output
0,people watch cricket,1
1,player was player,1
2,people write comment,0
3,cricket play comment,0


In [6]:
# people watch cricket player was write comment play
#[11100000]
#[00021000]
#[10000110]
#[00100011]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer()

In [9]:
bow = cv.fit_transform(df['Text'])

In [10]:
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [12]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [13]:
cv.transform(['people watch and write comment of cricket comment']).toarray()

array([[2, 1, 1, 0, 0, 0, 1, 1]])

In [14]:
# 2. N-Grams

In [15]:
v = CountVectorizer(ngram_range=(1,2))


In [16]:
bow = v.fit_transform(df['Text'])

In [17]:
df['Text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: Text, dtype: object

In [18]:
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [19]:
# Term Freqquency

## Inverse Document Frequency (IDF)

In [20]:
# TF(t,d) = (no. of occurunces of term t in document d)/ (total no. of terms in document d)

# example :
#d1 = 'people watch cricket'
#tf(people,d1) = 1/3

#d2 = 'player was player'
#tf(player,d2) = 2/3

In [21]:
#IDF(t) = log_e(total no. of documents / no. of documents with term t in it)

#example :

#d1 = 'people watch cricket'
#d2 = 'cricket was cricket'
#d3 = 'people write cricket'
#d4 = 'cricket play comment'

#tf(people) = 4/2

#tf(cricket) = 4/4


In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['Text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [27]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']


# NER (NAME ENTITY RECOGNITION)
    NER  is a NLP technique used to find important entities in a text. It is used to extract information from unstructured text data. It can be used to extract names of people, organizations, locations, dates, and other important information from text data.
    Why do we use NER? -> to convert unstructured text data into structured data. 
    Main Reasons: Automatically extract imp information, reduce manual work, help machines understand cpntext, improve search and retrieval, enhance data analysis, enable automation, support decision making, facilitate knowledge discovery, improve user experience, enable personalization, support compliance and regulation.


In [29]:
!pip install spacy
!python -m spacy download en_core_web_sm

   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.2 MB 3.6 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/14.2 MB 3.4 MB/s eta 0:00:04
   ------ --------------------------------- 2.4/14.2 MB 4.1 MB/s eta 0:00:03
   -------- ------------------------------- 3.1/14.2 MB 4.0 MB/s eta 0:00:03
   ----------- ---------------------------- 3.9/14.2 MB 3.9 MB/s eta 0:00:03
   -------------- ------------------------- 5.0/14.2 MB 4.2 MB/s eta 0:00:03
   --------------- ------------------------ 5.5/14.2 MB 4.4 MB/s eta 0:00:02
   ------------------- -------------------- 6.8/14.2 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 7.6/14.2 MB 4.2 MB/s eta 0:00:02
   ---------------------- ----------------- 8.1/14.2 MB 4.0 MB/s eta 0:00:02
   ------------------------- -------------- 8.9/14.2 MB 4.1 MB/s eta 0:00:02
   --------------------------- ------------ 9.7/14.2 MB 4.1 MB/s eta 0:00:02
   ---

In [31]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [32]:
text = "Barack Obama was born in Hawaii and became the 44th president of the United States."

doc = nlp(text)

for ent in doc.ents:
    print(ent.text,"->",ent.label_)

Barack Obama -> PERSON
Hawaii -> GPE
44th -> ORDINAL
the United States -> GPE


In [33]:
text2 = "Apple is looking at buying U.K. startup for $1 billion"

doc2 = nlp(text2)

for ent in doc2.ents:
    print(ent.text,"->",ent.label_)

Apple -> ORG
U.K. -> GPE
$1 billion -> MONEY


In [36]:
text3 = "Google CEO Sundar Pichai announced a $10 billion investment in India on 15th July 2025"

doc3 = nlp(text3)
for ent in doc3.ents:
    print(ent.text,"->",ent.label_)

Google -> ORG
Sundar Pichai -> PERSON
$10 billion -> MONEY
India -> GPE
15th July 2025 -> DATE


In [37]:
text3 = "Microsoft was founded by Bill Gates in 1995"

doc3 = nlp(text3)
for ent in doc3.ents:
    print(ent.text,"->",ent.label_)

Microsoft -> ORG
Bill Gates -> PERSON
1995 -> DATE


In [39]:
from googletrans import Translator
translator = Translator()

In [49]:
review = "Kal 15 August 2025 ko main Cafe Delhi Heights, Jaipur gaya tha apne dost Rahul Sharma ke saath. Waha ka Cold Coffee aur Margherita Pizza bahut tasty tha. Staff ne bataya ki unka special offer Independence Day ke occasion par ₹500 se upar ke order par chal raha hai. Overall, Cafe Delhi Heights ki service aur ambience kaafi amazing thi."

translated = await translator.translate(review,dest='en')


In [50]:
eng_review = translated.text
eng_review

'Yesterday on 15 August 2025, I went to Main Cafe Delhi Heights, Jaipur with my friend Rahul Sharma. The Cold Coffee and Margherita Pizza there was very tasty. The staff told that their special offer is running on orders above ₹500 on the occasion of Independence Day. Overall, the service and ambiance of Cafe Delhi Heights was quite amazing.'

In [51]:
doc = nlp(eng_review)

for ent in doc.ents:
    print(ent.text,"->",ent.label_)

Yesterday -> DATE
15 August 2025 -> DATE
Main Cafe Delhi Heights -> FAC
Jaipur -> GPE
Rahul Sharma -> PERSON
The Cold Coffee -> ORG
Margherita -> PERSON
Independence Day -> EVENT
Cafe Delhi Heights -> FAC


In [ ]:
#create a pattern  that will mask or replace mobile no. , account no. , email id  from customer complaint, use regular expression.

In [61]:
import re

def mask (text):
    
    text = re.sub(r'\b\d{10}\b','<MOBILE_NO>',text)
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b','<EMAIL_ID>',text)
    text = re.sub(r'\b\d{9,18}\b','<ACCOUNT_NO>',text)
    return text




In [62]:
text  = """
Hello, my name is Rohan. My mobile number is 9876543210.
My bank account number is 123456789012345.
Please contact me at rohan123@gmail.com regarding my issue.
"""

In [63]:
mask(text)

'\nHello, my name is Rohan. My mobile number is <MOBILE_NO>.\nMy bank account number is <ACCOUNT_NO>.\nPlease contact me at <EMAIL_ID> regarding my issue.\n'